Repository OffchainLabs/arbitrum-token-bridge, pull requests merged in 2022-12, with the labels that each got.

#515 fix: clean up eslint errors in UI and SDK
  .eslintrc.js
  packages/arb-token-bridge-ui/src/components/App/AppContext.tsx
  packages/arb-token-bridge-ui/src/components/TransactionsTable/TransactionsTableWithdrawalRow.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/DepositConfirmationDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenImportDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearchUtils.ts
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCard.tsx
  packages/arb-token-bridge-ui/src/components/common/Button.tsx
  packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
  packages/arb-token-bridge-ui/src/components/common/Tab.tsx
  packages/arb-token-bridge-ui/src/components/syncers/RetryableTxnsIncluder.tsx
  packages/arb-token-bridge-ui/src/state/app/onInitialize.ts
  packages/arb-token-bridge-ui/src/util/RetryableUtils.ts
  packages/arb-token-bridge-ui/src/util/fastBridges.ts
  packages/arb-token-bridge-ui/src/util/networks.ts
  packages/token-bridge-sdk/src/hooks/__tests__/useBalance.test.tsx
  packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
  packages/token-bridge-sdk/src/hooks/useBalance.ts
Labels: Type: Bug, Priority: P0 High, cla-signed

#516 fix: handle old withdrawals
  packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
  packages/token-bridge-sdk/src/withdrawals/fetchTokenWithdrawalsFromSubgraph.ts
Labels: cla-signed

#519 chore: remove inapplicable advisory from ignore list
  audit-ci.jsonc
  packages/arb-token-bridge-ui/package.json
  yarn.lock
Labels: Priority: P2 Low, cla-signed, Type: Security Advisory

#514 fix: properly add and remove token lists
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearchUtils.ts
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/token-bridge-sdk/src/hooks/arbTokenBridge.types.ts
  packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
Labels: cla-signed, Priority: P1 Medium, Type: Refactoring

#520 chore: add GRT to list of tokens requiring approval on L2
  packages/arb-token-bridge-ui/src/util/L2ApprovalUtils.ts
Labels: cla-signed

#524 chore: update grt info on whitelist era list
  packages/arb-token-bridge-ui/public/token-list-42161.json
Labels: cla-signed

#523 chore: change page title
  packages/arb-token-bridge-ui/public/index.html
Labels: cla-signed

#521 feat: add OpenSea to explore Arbitrum
  packages/arb-token-bridge-ui/public/images/explore-arbitrum/nft/opensea.webp
  packages/arb-token-bridge-ui/src/components/MainContent/ExploreArbitrumContent.ts
  packages/arb-token-bridge-ui/src/util/AnalyticsUtils.ts
Labels: cla-signed

#522 style: adjust ecosystem dropdown in header
  packages/arb-token-bridge-ui/src/components/common/Header.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderMenu.tsx
Labels: cla-signed

#512 chore: add PR template
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  packages/arb-token-bridge-ui/package.json
  packages/token-bridge-sdk/package.json
Labels: Priority: P2 Low, cla-signed, Type: Automation

#528 test: add test to check for token lists being valid
  .github/workflows/build-test.yml
  packages/arb-token-bridge-ui/src/__test__/tokenLists.test.ts
  packages/arb-token-bridge-ui/src/tokenLists.tsx
Labels: cla-signed

#530 build: update browserslist
  yarn.lock
Labels: Type: Dependencies, Priority: P2 Low, cla-signed

#511 feat: support token transfers through smart contract wallets
  packages/arb-token-bridge-ui/src/components/App/App.tsx
  packages/arb-token-bridge-ui/src/components/TransactionsTable/TransactionsTable.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
  packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
  packages/arb-token-bridge-ui/src/styles/tailwind.css
  packages/arb-token-bridge-ui/src/util/AddressUtils.ts
  packages/arb-token-bridge-ui/src/util/index.ts
  packages/arb-token-bridge-ui/tailwind.config.js
  packages/token-bridge-sdk/src/hooks/arbTokenBridge.types.ts
  packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
Labels: Type: New Feature, cla-signed, Priority: P1 Medium

#534 fix: adjust spacing in summary panel
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
Labels: cla-signed

#533 fix: pin commit of warningTokens.json
  packages/arb-token-bridge-ui/src/components/App/App.tsx
Labels: cla-signed

#537 chore: remove rinkeby stuff
  packages/arb-token-bridge-ui/.env.sample
  packages/arb-token-bridge-ui/public/token-list-421611.json
  packages/arb-token-bridge-ui/src/assets/HeaderArbitrumLogoRinkeby.webp
  packages/arb-token-bridge-ui/src/components/App/App.tsx
  packages/arb-token-bridge-ui/src/components/common/Notifications.tsx
  packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
  packages/arb-token-bridge-ui/src/state/app/actions.ts
  packages/arb-token-bridge-ui/src/tokenLists.tsx
  packages/arb-token-bridge-ui/src/util/modelProviderOpts.tsx
  packages/arb-token-bridge-ui/src/util/networks.ts
  packages/token-bridge-sdk/src/util/subgraph.ts
  readme.md
Labels: cla-signed

#535 fix: wrong network page changes
  packages/arb-token-bridge-ui/src/components/App/App.tsx
  packages/arb-token-bridge-ui/src/components/common/Button.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderNetworkNotSupported.tsx
  packages/arb-token-bridge-ui/src/components/common/MainNetworkNotSupported.tsx
  packages/arb-token-bridge-ui/tests/e2e/specs/switchNetworks.cy.ts
Labels: cla-signed

#538 chore: update twitter request faucet text
  packages/arb-token-bridge-ui/src/hooks/useTwitter.ts
Labels: cla-signed
