Repository OffchainLabs/arbitrum-token-bridge, pull requests merged in 2022-11, with the labels that each got.

#459 feat: improve the “wrong network” ui
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/src/components/App/App.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderNetworkInformation.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderNetworkNotSupported.tsx
  packages/arb-token-bridge-ui/src/components/common/MainNetworkNotSupported.tsx
  packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
  packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
  packages/arb-token-bridge-ui/src/state/app/actions.ts
  packages/arb-token-bridge-ui/src/state/app/state.ts
  packages/arb-token-bridge-ui/src/util/CommonUtils.ts
  packages/arb-token-bridge-ui/src/util/networks.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/switchNetworks.cy.ts
Labels: cla-signed

#493 feat: add tx cost estimator site link to charts & stats
  packages/arb-token-bridge-ui/src/components/common/Header.tsx
Labels: cla-signed

#486 ci: clean up config and check for code formatting
  .github/actions/restore-cache/action.yml
  .github/workflows/build-test.yml
  eslintrc.js
  package.json
  packages/arb-token-bridge-ui/craco.config.js
  packages/arb-token-bridge-ui/eslintrc.js
  packages/arb-token-bridge-ui/public/index.html
  packages/arb-token-bridge-ui/public/token-list-42161.json
  packages/arb-token-bridge-ui/public/token-list-421611.json
  packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalConfirmationDialog.tsx
  packages/arb-token-bridge-ui/tests/e2e/.eslintrc.js
  packages/arb-token-bridge-ui/tests/e2e/tsconfig.json
  packages/token-bridge-sdk/README.md
  packages/token-bridge-sdk/eslintrc.js
  packages/token-bridge-sdk/jsdoc.json
  packages/use-wallet/.prettierrc
  packages/use-wallet/src/index.ts
Labels: cla-signed

#495 fix: hardcode erc-20 deposit gas estimation
  packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
Labels: cla-signed

#471 fix: add short format for large numbers
  packages/arb-token-bridge-ui/src/components/TransferPanel/DepositCardSuccess.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCardExecuted.tsx
  packages/arb-token-bridge-ui/src/util/NumberUtils.ts
  packages/arb-token-bridge-ui/src/util/__tests__/NumberUtils.test.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/login.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
Labels: cla-signed

#497 test: fix numbers wrongly formatted in non-english browser
  packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/depositETH.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/withdrawETH.cy.ts
Labels: cla-signed

#499 fix: add vercel config
  packages/arb-token-bridge-ui/src/components/TermsOfService/TermsOfService.tsx
  packages/arb-token-bridge-ui/tests/e2e/specs/vercel.cy.ts
  vercel.json
Labels: cla-signed

#470 test: add e2e tests for amount query param
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/urlQueryParam.cy.ts
  packages/arb-token-bridge-ui/tests/support/commands.ts
  packages/arb-token-bridge-ui/tests/support/common.ts
  yarn.lock
Labels: cla-signed

#503 style: change footer "learn more" link font-size
  packages/arb-token-bridge-ui/src/components/common/Footer.tsx
Labels: cla-signed

#504 feat: Add sperax to Arbitrum explore
  packages/arb-token-bridge-ui/public/images/explore-arbitrum/defi/sperax.webp
  packages/arb-token-bridge-ui/src/components/MainContent/ExploreArbitrumContent.ts
  packages/arb-token-bridge-ui/src/util/AnalyticsUtils.ts
Labels: cla-signed

#505 fix: update description meta tag
  packages/arb-token-bridge-ui/public/index.html
Labels: cla-signed

#496 test: update tests for withdrawals to point to arbitrum one
  packages/token-bridge-sdk/src/withdrawals/__test__/fetchETHWithdrawalsFromEventLogs.test.ts
  packages/token-bridge-sdk/src/withdrawals/__test__/fetchETHWithdrawalsFromSubgraph.test.ts
  packages/token-bridge-sdk/src/withdrawals/__test__/fetchETHWithdrawalsTestHelpers.ts
  packages/token-bridge-sdk/src/withdrawals/__test__/fetchTokenWithdrawalsFromEventLogs.test.ts
  packages/token-bridge-sdk/src/withdrawals/__test__/fetchTokenWithdrawalsFromSubgraph.test.ts
  packages/token-bridge-sdk/src/withdrawals/__test__/fetchTokenWithdrawalsTestHelpers.ts
Labels: cla-signed

#465 chore: use one eslint config file
  .eslintignore
  .eslintrc.js
  eslintrc.js
  packages/arb-token-bridge-ui/craco.config.js
  packages/arb-token-bridge-ui/eslintrc.js
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
  packages/arb-token-bridge-ui/tests/e2e/.eslintrc.js
  packages/arb-token-bridge-ui/tests/e2e/specs/urlQueryParam.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/tsconfig.json
  packages/arb-token-bridge-ui/tsconfig.json
  packages/token-bridge-sdk/eslintrc.js
  packages/token-bridge-sdk/package.json
  packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
  packages/token-bridge-sdk/tsconfig.json
  tsconfig.base.json
  tsconfig.eslint.json
  yarn.lock
Labels: cla-signed

#507 chore: remove obsolete cex
  packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialogContent.ts
  packages/arb-token-bridge-ui/src/util/AnalyticsUtils.ts
Labels: cla-signed

#508 chore: add GRT to tokens requiring L2 approval on Goerli
  packages/arb-token-bridge-ui/src/util/L2ApprovalUtils.ts
Labels: cla-signed

#510 fix: use deposit request for token deposits
  packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
Labels: cla-signed

#462 refactor: move erc-20 balance management to useBalance
  packages/arb-token-bridge-ui/src/components/TransferPanel/DepositCardSuccess.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMainUtils.ts
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCardExecuted.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/useTokenBalances.ts
  packages/arb-token-bridge-ui/src/components/syncers/ArbTokenBridgeStoreSync.tsx
  packages/arb-token-bridge-ui/src/hooks/useTokenDecimals.ts
  packages/token-bridge-sdk/src/hooks/__tests__/useBalance.test.tsx
  packages/token-bridge-sdk/src/hooks/arbTokenBridge.types.ts
  packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
  packages/token-bridge-sdk/src/hooks/useBalance.ts
  packages/token-bridge-sdk/src/hooks/useGasPrice.ts
  packages/token-bridge-sdk/src/util/index.ts
Labels: cla-signed

#513 chore: add new advisory
  audit-ci.jsonc
Labels: Priority: P0 High, cla-signed, Type: Security Advisory

#509 chore: update eslint packages to latest
  .eslintrc.js
  packages/arb-token-bridge-ui/package.json
  packages/token-bridge-sdk/package.json
  yarn.lock
Labels: cla-signed, Priority: P1 Medium, Type: Tools
