Repository OffchainLabs/arbitrum-token-bridge, pull requests merged in 2023-04, with the labels that each got.

#654 chore: turn off april fools after midnight
  packages/arb-token-bridge-ui/src/components/common/Notifications.tsx
  packages/arb-token-bridge-ui/src/components/syncers/ThemeIncluder.tsx
  packages/arb-token-bridge-ui/src/styles/purple.css
Labels: cla-signed

#655 fix: added padding around notification
  packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionStatusInfo.tsx
Labels: cla-signed

#658 fix: e2e
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/public/images/EthereumLogo.webp
  packages/arb-token-bridge-ui/src/components/App/WelcomeDialog.tsx
  packages/arb-token-bridge-ui/src/components/MainContent/ExploreArbitrum.tsx
  packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistory.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/DepositCard.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCard.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalConfirmationDialog.tsx
  packages/arb-token-bridge-ui/src/components/common/BridgesTable.tsx
  packages/arb-token-bridge-ui/src/components/common/Footer.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderNetworkInformation.tsx
  packages/arb-token-bridge-ui/src/components/common/MainNetworkNotSupported.tsx
  packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
  packages/arb-token-bridge-ui/src/util/networks.ts
  packages/arb-token-bridge-ui/synpress.config.ts
  packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
  packages/arb-token-bridge-ui/tests/e2e/tsconfig.json
  packages/arb-token-bridge-ui/tests/support/commands.ts
  packages/arb-token-bridge-ui/tests/support/common.ts
Labels: cla-signed, Priority: P1 Medium

#637 refactor: move deposits and withdrawals logic from sdk to ui
  .github/workflows/build-test.yml
  packages/arb-token-bridge-ui/jest.config.js
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/setupTests.ts
  packages/arb-token-bridge-ui/src/components/syncers/RetryableTxnsIncluder.tsx
  packages/arb-token-bridge-ui/src/hooks/useDeposits.ts
  packages/arb-token-bridge-ui/src/hooks/useWithdrawals.ts
  packages/arb-token-bridge-ui/src/pages/api/deposits.ts
  packages/arb-token-bridge-ui/src/pages/api/withdrawals.ts
  packages/arb-token-bridge-ui/src/util/SubgraphUtils.ts
  packages/arb-token-bridge-ui/src/util/deposits/__tests__/fetchDepositsFromSubgraph.test.ts
  packages/arb-token-bridge-ui/src/util/deposits/__tests__/fetchDepositsTestHelpers.ts
  packages/arb-token-bridge-ui/src/util/deposits/fetchDeposits.ts
  packages/arb-token-bridge-ui/src/util/deposits/fetchDepositsFromSubgraph.ts
  packages/arb-token-bridge-ui/src/util/deposits/helpers.ts
  packages/arb-token-bridge-ui/src/util/index.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/__tests__/fetchETHWithdrawalsFromEventLogs.test.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/__tests__/fetchETHWithdrawalsTestHelpers.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/__tests__/fetchTokenWithdrawalsFromEventLogs.test.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/__tests__/fetchWithdrawalsFromSubgraph.test.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/__tests__/fetchWithdrawalsTestHelpers.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/fetchETHWithdrawalsFromEventLogs.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/fetchTokenWithdrawalsFromEventLogs.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/fetchWithdrawals.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/fetchWithdrawalsFromSubgraph.ts
  packages/arb-token-bridge-ui/src/util/withdrawals/helpers.ts
  packages/token-bridge-sdk/package.json
  packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
  packages/token-bridge-sdk/src/index.ts
  packages/token-bridge-sdk/src/util/index.ts
  packages/token-bridge-sdk/src/withdrawals/index.ts
  yarn.lock
Labels: cla-signed

#667 chore: update lockfile and run formatting
  packages/arb-token-bridge-ui/src/components/App/WelcomeDialog.tsx
  packages/arb-token-bridge-ui/src/components/MainContent/ExploreArbitrumContent.ts
  packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TableActionHeader.tsx
  packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TransactionsTable.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/DepositCardPending.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialogContent.ts
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenButton.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenImportDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCardConfirmed.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCardUnconfirmed.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalConfirmationDialog.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderConnectWalletButton.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderMenu.tsx
  packages/arb-token-bridge-ui/src/components/common/Layout.tsx
  packages/arb-token-bridge-ui/src/components/common/MainNetworkNotSupported.tsx
  packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
  packages/arb-token-bridge-ui/src/components/common/SidePanel.tsx
  packages/arb-token-bridge-ui/src/util/AnalyticsUtils.ts
  packages/arb-token-bridge-ui/src/util/fastBridges.ts
  yarn.lock
Labels: cla-signed

#668 fix: banner alignment on mobile
  packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionStatusInfo.tsx
Labels: cla-signed

#669 feat: remove Low balance and Explore dialogs
  packages/arb-token-bridge-ui/src/components/MainContent/MainContent.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/components/common/Footer.tsx
  packages/arb-token-bridge-ui/src/styles/purple.css
  packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/importToken.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/readClassicDeposits.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/switchNetworks.cy.ts
  packages/arb-token-bridge-ui/tests/support/commands.ts
Labels: cla-signed

#582 ci: run e2e tests
  .github/workflows/build-test.yml
  Dockerfile
  docker-compose.ci.yml
  package.json
  packages/arb-token-bridge-ui/.e2e.env.sample
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
  packages/arb-token-bridge-ui/src/pages/_app.tsx
  packages/arb-token-bridge-ui/synpress.config.ts
  packages/arb-token-bridge-ui/tests/e2e/.eslintrc.js
  packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/approveToken.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/depositETH.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/importToken.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/login.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/readClassicDeposits.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/switchNetworks.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/txHistory.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/urlQueryParam.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/withdrawETH.cy.ts
  packages/arb-token-bridge-ui/tests/support/commands.ts
  packages/arb-token-bridge-ui/tests/support/common.ts
  packages/arb-token-bridge-ui/tests/support/index.ts
  yarn.lock
Labels: cla-signed

#696 ci: run tests based on changed folder/file
  .github/workflows/build-test.yml
Labels: cla-signed

#692 test: e2e independent of Metamask state
  packages/arb-token-bridge-ui/synpress.config.ts
  packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/approveToken.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/importToken.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/login.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/readClassicDeposits.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/switchNetworks.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/txHistory.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/withdrawETH.cy.ts
  packages/arb-token-bridge-ui/tests/support/commands.ts
  packages/arb-token-bridge-ui/tests/support/common.ts
  packages/arb-token-bridge-ui/tests/support/index.ts
Labels: cla-signed

#687 chore: update SWR to v2
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/src/hooks/useDeposits.ts
  packages/arb-token-bridge-ui/src/hooks/useERC20L1Address.ts
  packages/arb-token-bridge-ui/src/hooks/useWithdrawals.ts
  packages/arb-token-bridge-ui/src/tokenLists.tsx
  packages/token-bridge-sdk/package.json
  packages/token-bridge-sdk/src/hooks/useBalance.ts
  yarn.lock
Labels: Type: Dependencies, Priority: P2 Low, cla-signed, Type: Housekeeping

#690 chore: added contribution guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  package.json
  packages/arb-token-bridge-ui/README.md
  packages/arb-token-bridge-ui/package.json
  packages/use-wallet/package.json
  readme.md
Labels: Priority: P2 Low, cla-signed, Type: Housekeeping

#630 feat: bridge preferences and network stats
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/src/components/App/AppContext.tsx
  packages/arb-token-bridge-ui/src/components/MainContent/ArbitrumStats.tsx
  packages/arb-token-bridge-ui/src/components/MainContent/MainContent.tsx
  packages/arb-token-bridge-ui/src/components/common/BridgesTable.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
  packages/arb-token-bridge-ui/src/components/common/PreferencesDialog.tsx
  packages/arb-token-bridge-ui/src/components/common/SidePanel.tsx
  packages/arb-token-bridge-ui/src/components/common/StatusBadge.tsx
  packages/arb-token-bridge-ui/src/components/common/atoms/Loader.tsx
  packages/arb-token-bridge-ui/src/components/common/atoms/Radio.tsx
  packages/arb-token-bridge-ui/src/components/common/atoms/Switch.tsx
  packages/arb-token-bridge-ui/src/hooks/useArbQueryParams.tsx
  packages/arb-token-bridge-ui/src/hooks/useArbStats.ts
  packages/arb-token-bridge-ui/src/hooks/useTheme.ts
  packages/arb-token-bridge-ui/src/pages/api/arbstats.ts
  packages/arb-token-bridge-ui/src/styles/purple.css
  packages/arb-token-bridge-ui/src/util/networks.ts
  packages/arb-token-bridge-ui/tailwind.config.js
  yarn.lock
Labels: Type: New Feature, Priority: P2 Low, cla-signed

#716 fix: broken link in README
  README.md
Labels: cla-signed

#726 chore: remove twitter faucet link
  packages/arb-token-bridge-ui/src/components/common/Notifications.tsx
  packages/arb-token-bridge-ui/src/hooks/useTwitter.ts
Labels: Priority: P2 Low, cla-signed

#722 feat: remove transaction history tooltip
  packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistoryTooltip.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
Labels: cla-signed

#727 fix: network selection box hover css
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
  packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
  packages/arb-token-bridge-ui/src/styles/tailwind.css
Labels: Priority: P2 Low, cla-signed

#706 refactor: delete old CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: cla-signed

#651 refactor: wagmi and rainbowkit
  .eslintrc.js
  .github/actions/build-artifacts/cache/action.yml
  .github/actions/build-artifacts/restore/action.yml
  .gitignore
  audit-ci.jsonc
  package.json
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/src/components/App/App.tsx
  packages/arb-token-bridge-ui/src/components/TransactionHistory/PendingTransactions.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
  packages/arb-token-bridge-ui/src/components/common/Dialog.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderConnectWalletButton.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderNetworkInformation.tsx
  packages/arb-token-bridge-ui/src/components/common/MainNetworkNotSupported.tsx
  packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
  packages/arb-token-bridge-ui/src/hooks/useClaimWithdrawal.ts
  packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
  packages/arb-token-bridge-ui/src/hooks/useRedeemRetryable.ts
  packages/arb-token-bridge-ui/src/pages/_app.tsx
  packages/arb-token-bridge-ui/src/styles/tailwind.css
  packages/arb-token-bridge-ui/src/util/AnalyticsUtils.ts
  packages/arb-token-bridge-ui/src/util/modelProviderOpts.tsx
  packages/arb-token-bridge-ui/src/util/networks.ts
  packages/arb-token-bridge-ui/src/util/wagmi/setup.ts
  packages/arb-token-bridge-ui/src/util/wagmi/wagmiAdditionalNetworks.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/login.cy.ts
  packages/arb-token-bridge-ui/tests/e2e/specs/switchNetworks.cy.ts
  packages/arb-token-bridge-ui/tests/support/commands.ts
  packages/token-bridge-sdk/package.json
  packages/token-bridge-sdk/src/hooks/useBalance.ts
  packages/use-wallet/.gitignore
  packages/use-wallet/.prettierrc
  packages/use-wallet/README.md
  packages/use-wallet/package.json
  packages/use-wallet/src/index.ts
  tsconfig.eslint.json
  yarn.lock
Labels: cla-signed, Priority: P1 Medium, Type: Refactoring

#714 fix: 403 issue in fetching network TPS
  packages/arb-token-bridge-ui/src/components/MainContent/ArbitrumStats.tsx
  packages/arb-token-bridge-ui/src/hooks/useArbStats.ts
  packages/arb-token-bridge-ui/src/hooks/useNetworkTPS.ts
  packages/arb-token-bridge-ui/src/pages/api/arbstats.ts
  packages/arb-token-bridge-ui/src/util/networks.ts
Labels: cla-signed

#744 fix: add local chains when in dev
  packages/arb-token-bridge-ui/src/util/CommonUtils.ts
Labels: cla-signed

#723 chore: enable react strict mode
  packages/arb-token-bridge-ui/next.config.js
Labels: Priority: P2 Low, cla-signed

#686 feat: set up PostHog
  packages/arb-token-bridge-ui/package.json
  packages/arb-token-bridge-ui/src/pages/_app.tsx
  yarn.lock
Labels: Type: Dependencies, cla-signed, Type: Tools

#741 fix: clear confirmed withdrawals on account change
  packages/arb-token-bridge-ui/src/state/app/state.ts
  packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
Labels: cla-signed

#763 fix: reverted the additional UI check which failed E2E
  packages/arb-token-bridge-ui/src/state/app/state.ts
Labels: cla-signed

#745 fix: history stuck on loading if token deposit pending
  packages/arb-token-bridge-ui/src/util/deposits/helpers.ts
  packages/token-bridge-sdk/src/hooks/useTransactions.ts
Labels: cla-signed

#771 fix: don't cache token data if something fails
  packages/token-bridge-sdk/src/util/index.ts
Labels: cla-signed

#777 fix: only show connect modal after TOS is accepted
  packages/arb-token-bridge-ui/src/components/App/App.tsx
  packages/arb-token-bridge-ui/src/components/App/WelcomeDialog.tsx
  packages/arb-token-bridge-ui/src/components/common/Dialog.tsx
  packages/arb-token-bridge-ui/src/components/common/Layout.tsx
  packages/arb-token-bridge-ui/src/constants.ts
  packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
Labels: cla-signed

#780 chore: uninstall @tailwindcss/forms
  packages/arb-token-bridge-ui/package.json
  yarn.lock
Labels: cla-signed, external contribution

#750 feat: add posthog events
  packages/arb-token-bridge-ui/.env.local.sample
  packages/arb-token-bridge-ui/src/components/MainContent/ExploreArbitrum.tsx
  packages/arb-token-bridge-ui/src/components/TransactionHistory/FailedTransactionsWarning.tsx
  packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionStatusInfo.tsx
  packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TransactionsTableWithdrawalRow.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/DepositConfirmationDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialog.tsx
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/components/common/BridgesTable.tsx
  packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
  packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
  packages/arb-token-bridge-ui/src/hooks/useRedeemRetryable.ts
  packages/arb-token-bridge-ui/src/util/AnalyticsUtils.ts
Labels: cla-signed

#778 fix: improve token data caching
  packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearchUtils.ts
  packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
  packages/arb-token-bridge-ui/src/token-bridge-sdk/hooks/arbTokenBridge.types.ts
  packages/arb-token-bridge-ui/src/token-bridge-sdk/hooks/useArbTokenBridge.ts
  packages/arb-token-bridge-ui/src/token-bridge-sdk/index.ts
  packages/arb-token-bridge-ui/src/token-bridge-sdk/util/index.ts
Labels: cla-signed
